# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c599e327fb9121f0db96eb6003863b97bcb2887fa3e00e1727047cbbf1bcff48d1a9286e88e6c94b018cdf4fe31e100b857fa99ffde0fdc3239bcd2359ec48

test:
  secret_key_base: bafb7fde91fe3a1a35d351d2909e6930161aae51997ed4739b8984e9b542497403c97db5547086fc128339126286ca0741a07ecfad3c8f62addaaa15f3f97dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
